### ISSUE TITLE
Use Character N-Gram Approach for Word Embeddings

### ISSUE THREAD

**Issue by asittampalam** [eonum/medword#6]
Use a character level n-gram approach in order to include sub-word information. This might solve the compound word splitting problem. Additionally it's possible to obtain vectors for words which aren't in the vocabulary using a sum of the character n-gram vectors.

https://arxiv.org/pdf/1607.04606.pdf

**Comment by tschimbr** [comment]
See also https://www.youtube.com/watch?v=B4v545V3Dq0 (starting at around the middle of the lecture)

**Comment by tschimbr** [comment]
Byte Pair Encoding

**Comment by fabmue** [comment]
char n-gram approach (fastText) implemented in 334571722f308c3dc6054d0e72acc96c19973824, new issue for Byte Pair Encoding approach
